version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:17.0.1
      
jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          name: Install dependencies
          cd project-power-smart
          npm install
      - run: |
          name: Run tests
          npm run test

workflows:
  my-custom-workflow:
    jobs:
      - build