version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:17.0.1
      
jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - name: Install dependencies
      - run: |
          cd project-power-smart
          npm install
      - name: Run tests
      - run:
          npm run test
          
workflows:
  my-custom-workflow:
    jobs:
      - build