version: 2
jobs:
  build:
    macos:
      xcode: "11.3.0"

    working_directory: ~/repo

    steps:
      - checkout

      # Set up environment
      - run: npm install -g react-native-cli
      - run: npm install -g detox-cli
      - run: brew tap wix/brew
      - run: brew install applesimutils

      # run unit tests
      - run: yarn install
      - run: yarn test

      # run E2E tests
      - run: cd ios && pod install && cd ..
      - run: detox build --configuration ios.sim.release
      - run: detox test --configuration ios.sim.release --cleanup