version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:17.0.1
      
jobs:
  build:
    environment:
      email: jondoe@organization.com
      password: pass123
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          cd project-power-smart
          npm install

workflows:
  my-custom-workflow:
    jobs:
      - build